### ISSUE TITLE
Rechallenge Design 🖼

### ISSUE THREAD

**Issue by Nassim-dev** [Raito-HETIC/raito#13]
# **EPIC**  | **Design** 🖼
<br>

## Designs and assets
Figma link: ...

## TODO 
- [ ] Terminer la première version des maquettes v.1
- [ ] Tester les maquettes avec des personnes ext. 
- [ ] Rédiger les feedbacks dans le wiki pour améliorer les maquettes

**Comment by Nassim-dev** [comment]
• Pour le 17/05 : 
@DFarau et @Pao-La-CCC vous allez travailler ensemble pour réunir vos travaux afin d'avoir une vraie version 1.0 des maquettes. 
@chloe-dst a prévu de prendre du temps pour affiner les maquettes en fin de journée, avec son oeil extérieur.
