### ISSUE TITLE
Design 🖼

### ISSUE THREAD

**Issue by Nassim-dev** [Raito-HETIC/raito#4]
# **EPIC**  | **Design** 🖼
<br>

## Designs and assets
Figma link : ...

## TODO 
- [ ] Terminer la première version des maquettes v.1
- [ ] Tester les maquettes avec des personnes ext. 
- [ ] Rédiger les feedbacks dans le wiki pour améliorer les maquettes

**Comment by Nassim-dev** [comment]
Hey @valentinmariot I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/raito-624d8279b2266d001ccada8e/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
